version: 0.0
os: linux

files:
  - source: target/CodeDeployDemo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
